"""initial schema

Revision ID: 85162e749fc9
Revises:
Create Date: 2026-09-27 20:47:49.579868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "85162e749fc9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "school",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "address",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        ),
        sa.Column(
            "phone",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        ),
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        ),
        sa.Column(
            "logo_url",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        ),
        sa.Column(
            "timezone",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                name="schoolstatus"
            ),
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=True),
        sa.Column(
            "name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "password_hash",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum(
                "SUPER_ADMIN",
                "SCHOOL_ADMIN",
                "TEACHER",
                "ACCOUNTANT",
                "PARENT",
                "STUDENT",
                name="userroles",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "INVITED",
                "ACTIVE",
                "SUSPENDED",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_user_school_id"),
        "user",
        ["school_id"],
        unique=False,
    )

    op.create_table(
        "schoolapplication",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "school_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "contact_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "contact_email",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        ),
        sa.Column(
            "contact_phone",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        ),
        sa.Column(
            "expected_students",
            sa.Integer(),
            nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="schoolapplicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust ###

    op.drop_table("schoolapplication")
    op.drop_index(
        op.f("ix_user_school_id"),
        table_name="user",
    )
    op.drop_table("user")
    op.drop_table("school")

    # ### end Alembic commands ###